application: ilfoscores
version: 1
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: webapp2
  version: '2.5.1'

handlers:
- url: /images
  static_dir: images
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: ilfo_app.application

builtins:
- remote_api: on
