"""Ilfo Score Generator - Config Info.

Restaurant names and URLs.
"""

__author__ = 'tbowland@google.com (Taylor Bowland)'

REST_DICT = {
    'Beverly Hills': {},
    'Burlingame': {},
    'Carmel': {},
    'Coronado': {},
    'Corte Madera': {},
    'Del Mar': {},
    'Greenwood Village': {},
    'Irvine': {},
    'Las Vegas': {},
    'Canaletto Las Vegas': {},
    'Manhattan Beach': {},
    'Canaletto Newport Beach': {},
    'Palo Alto': {},
    'Pasadena': {},
    'Reston': {},
    'Roseville': {},
    'Sacramento': {},
    'San Francisco': {},
    'San Jose': {},
    'Santa Monica': {},
    'Seattle': {},
    'Walnut Creek': {}
    }

CITYSEARCH_URLS = [
    ('Beverly Hills',
     'http://losangeles.citysearch.com/profile/109680/beverly_hills_ca/il_fornaio.html'),
    ('Burlingame',
     'http://sanfrancisco.citysearch.com/profile/830936/burlingame_ca/il_fornaio.html'),
    ('Carmel',
     'http://national.citysearch.com/profile/819158/carmel_by_the_sea_ca/il_fornaio.html'),
    ('Coronado',
     'http://sandiego.citysearch.com/profile/32551744/coronado_ca/il_fornaio.html'),
    ('Corte Madera',
     'http://sanfrancisco.citysearch.com/profile/1046049/corte_madera_ca/il_fornaio.html'),
    ('Del Mar', None),
    ('Greenwood Village',
     'http://denver.citysearch.com/profile/36546482/greenwood_village_co/il_fornaio.html'),
    ('Irvine',
     'http://orangecounty.citysearch.com/profile/40104788/irvine_ca/il_fornaio.html'),
    ('Las Vegas',
     'http://lasvegas.citysearch.com/profile/32821985/las_vegas_nv/ilfornaio.html'),
    ('Canaletto Las Vegas',
     'http://lasvegas.citysearch.com/profile/7023200/las_vegas_nv/canaletto.html'),
    ('Manhattan Beach',
     'http://losangeles.citysearch.com/profile/11473289/manhattan_beach_ca/il_fornaio.html'),
    ('Canaletto Newport Beach',
     'http://orangecounty.citysearch.com/profile/638228960/newport_beach_ca/canaletto_ristorante_veneto.html'),
    ('Palo Alto',
     'http://siliconvalley.citysearch.com/profile/920097/palo_alto_ca/il_fornaio.html'),
    ('Pasadena',
     'http://losangeles.citysearch.com/profile/237461/pasadena_ca/il_fornaio.html'),
    ('Reston', None),
    ('Roseville',
     'http://sacramento.citysearch.com/profile/32694076/roseville_ca/il_fornaio.html'),
    ('Sacramento',
     'http://sacramento.citysearch.com/profile/1241003/sacramento_ca/il_fornaio.html'),
    ('San Francisco',
     'http://sanfrancisco.citysearch.com/profile/662189470/san_francisco_ca/il_fornaio_san_francisco.html'),
    ('San Jose',
     'http://siliconvalley.citysearch.com/profile/1102857/san_jose_ca/il_fornaio.html'),
    ('Santa Monica',
     'http://losangeles.citysearch.com/profile/157241/santa_monica_ca/il_fornaio.html'),
    ('Seattle', None),
    ('Walnut Creek',
     'http://eastbay.citysearch.com/profile/1004665/walnut_creek_ca/il_fornaio.html')
    ]

ZAGAT_URLS = [
    ('Beverly Hills', 'http://www.zagat.com/r/il-fornaio-beverly-hills'),
    ('Burlingame', 'http://www.zagat.com/r/il-fornaio-burlingame'),
    ('Carmel', 'http://www.zagat.com/r/il-fornaio-carmel'),
    ('Coronado', 'http://www.zagat.com/r/il-fornaio-coronado'),
    ('Corte Madera', 'http://www.zagat.com/r/il-fornaio-corte-madera'),
    ('Del Mar', 'http://www.zagat.com/r/il-fornaio-del-mar'),
    ('Greenwood Village', 'http://www.zagat.com/r/il-fornaio-greenwood-village'),
    ('Irvine', 'http://www.zagat.com/r/il-fornaio-irvine'),
    ('Las Vegas', 'http://www.zagat.com/r/n/il-fornaio-las-vegas/reviews'),
    ('Canaletto Las Vegas', 'http://www.zagat.com/r/canaletto-las-vegas'),
    ('Manhattan Beach', 'http://www.zagat.com/r/il-fornaio-manhattan-beach'),
    ('Canaletto Newport Beach', 'http://www.zagat.com/r/canaletto-newport-beach'),
    ('Palo Alto', 'http://www.zagat.com/r/il-fornaio-palo-alto'),
    ('Pasadena', 'http://www.zagat.com/r/il-fornaio-pasadena'),
    ('Reston', 'http://www.zagat.com/r/il-fornaio-reston'),
    ('Roseville', 'http://www.zagat.com/r/il-fornaio-roseville'),
    ('Sacramento', 'http://www.zagat.com/r/il-fornaio-sacramento'),
    ('San Francisco', 'http://www.zagat.com/r/il-fornaio-san-francisco'),
    ('San Jose', 'http://www.zagat.com/r/il-fornaio-san-jose'),
    ('Santa Monica', 'http://www.zagat.com/r/il-fornaio-santa-monica'),
    ('Seattle', 'http://www.zagat.com/r/il-fornaio-seattle'),
    ('Walnut Creek', 'http://www.zagat.com/r/il-fornaio-walnut-creek')
    ]



#GOOGLE_URLS = [
#    'http://maps.google.com/maps/place?um=1&ie=UTF-8&q=il+fornaio+beverly+hills&fb=1&gl=us&hq=il+fornaio&hnear=0x80c2bc04d6d147ab:0xd6c7c379fd081ed1,Beverly+Hills,+CA&cid=14143913471344417505&ei=HmqKTsazPNDFsQLvv5ifBA&sa=X&oi=local_result&ct=placepage-link&resnum=1&ved=0CC4Q4gkwAA',
#    'http://maps.google.com/maps/place?hl=en&expIds=25657,25901,26446,26515&sugexp=ldymls&xhr=t&cp=13gl=us&um=1&ie=UTF-8&q=il+fornaio+burlingame&fb=1&gl=us&hq=il+fornaio&hnear=Burlingame,+CA&cid=6276834753469801992',
#    'http://maps.google.com/maps/place?hl=en&gl=us&um=1&ie=UTF-&q=il+fornaio+carmel+ca&fb=1&gl=us&hq=il+fornaio&hnear=Carmel-by-the-Sea,+CA&cid=4749944479599727646',
#    'http://maps.google.com/maps/place?hl=en&um=1&ie=UTF-&q=il+fornaio+coronado+ca&fb=1&gl=us&hq=il+fornaio&hnear=Coronado,+CA&cid=13354997451369476505&pcsi=13354997451369476505,1',
#    'http://maps.google.com/maps/place?um=1&ie=UTF-8&q=il+fornaio+corte+madera&fb=1&gl=us&hq=il+fornaio&hnear=0x8085960964a3862b:0x548250194c97012,Corte+Madera,+CA&cid=15068498351832914177&ei=l5iKTqPgA4ijsQK19JSbBA&sa=X&oi=local_result&ct=placepage-link&resnum=1&ved=0CCEQ4gkwAA',
#    'http://maps.google.com/maps/place?hl=en&gl=us&um=1&ie=UTF-&q=il+fornaio+del+mar+ca&fb=1&gl=us&hq=il+fornaio&hnear=Del+Mar,+CA&cid=11103761820061139276',
#    'http://maps.google.com/maps/place?hl=en&expIds=25657,25901,26446,26515&sugexp=ldymls&xhr=t&cp=14gl=us&um=1&ie=UTF-8&q=il+fornaio+greenwood+village&fb=1&gl=us&hq=il+fornaio&hnear=Greenwood+Village,+CO&cid=2905474607142858959',
#    'http://maps.google.com/maps/place?um=1&ie=UTF-8&q=il+fornaio+irvine&fb=1&gl=us&hq=il+fornaio&hnear=0x80dcdd0e689140e3:0xa77ab575604a9a39,Irvine,+CA&cid=14292743766466508317&ei=epiKTviuOuWMsAKNp-2VBA&sa=X&oi=local_result&ct=placepage-link&resnum=1&ved=0CDQQ4gkwAA',
#    'http://maps.google.com/maps/place?hl=en&expIds=25657,25901,26446,26515&sugexp=ldymls&xhr=t&cp=14gl=us&um=1&ie=UTF-8&q=il+fornaio+las+vegas&fb=1&gl=us&hq=il+fornaio&hnear=Las+Vegas,+NV&cid=5413980147627228611',
#    'http://maps.google.com/maps/place?hl=en&gl=us&um=1&ie=UTF-&q=canaletto+las+vegas&fb=1&gl=us&hq=canaletto&hnear=Las+Vegas,+NV&cid=17710884667690553637&pcsi=17710884667690553637,1',
#    'http://maps.google.com/maps/place?hl=en&expIds=25657,25901,26446,26515&sugexp=ldymls&xhr=t&cp=13gl=us&um=1&ie=UTF-8&q=il+fornaio+manhattan+beach&fb=1&gl=us&hq=il+fornaio&hnear=Manhattan+Beach,+CA&cid=8746776438526986899&pcsi=8746776438526986899,1',
#    'http://maps.google.com/maps/place?hl=en&expIds=25657,25901,26446,26515&sugexp=ldymls&xhr=t&cp=11gl=us&um=1&ie=UTF-8&q=canaletto+newport+beach&fb=1&gl=us&hq=canaletto&hnear=Newport+Beach,+CA&cid=13657496812975172871',
#    'http://maps.google.com/maps/place?hl=en&expIds=25657,25901,26446,26515&sugexp=ldymls&xhr=t&cp=12gl=us&um=1&ie=UTF-8&q=il+fornaio+palo+alto&fb=1&gl=us&hq=il+fornaio&hnear=Palo+Alto,+CA&cid=13654242828553017515',
#    'http://maps.google.com/maps/place?hl=en&expIds=25657,25901,26446,26515&sugexp=ldymls&xhr=t&cp=15gl=us&um=1&ie=UTF-8&q=il+fornaio+pasadena&fb=1&gl=us&hq=il+fornaio&hnear=Pasadena,+CA&cid=9892911117622564265&pcsi=9892911117622564265,1',
#    'http://maps.google.com/maps/place?hl=en&expIds=25657,25901,26446,26515&sugexp=ldymls&xhr=t&cp=19gl=us&um=1&ie=UTF-8&q=il+fornaio+reston+va&fb=1&gl=us&hq=il+fornaio&hnear=Reston,+VA&cid=9754942575320385396&pcsi=9754942575320385396,1',
#    'http://maps.google.com/maps/place?gl=us&hl=en&um=1&ie=UTF-&q=il+fornaio+roseville+ca&fb=1&gl=us&hq=il+fornaio&hnear=Roseville,+CA&cid=2098979100695146691&pcsi=2098979100695146691,1',
#    'http://maps.google.com/maps/place?hl=en&expIds=25657,25901,26446,26515&sugexp=ldymls&xhr=t&cp=14gl=us&um=1&ie=UTF-8&q=il+fornaio+sacramento&fb=1&gl=us&hq=il+fornaio&hnear=Sacramento,+CA&cid=16108666349360360117&pcsi=16108666349360360117,1',
#    'http://maps.google.com/maps/place?hl=en&expIds=25657,25901,26446,26515&sugexp=ldymls&xhr=t&cp=12gl=us&um=1&ie=UTF-8&q=il+fornaio+san+francisco&fb=1&gl=us&hq=il+fornaio&hnear=San+Francisco,+CA&cid=10742244364349724252',
#    'http://maps.google.com/maps/place?hl=en&expIds=25657,25901,26446,26515&sugexp=ldymls&xhr=t&cp=16g=us&um=1&ie=UTF-8&q=il+fornaio+san+jose&fb=1&gl=us&hq=il+fornaio&hnear=San+Jose,+CA&cid=12746475122430218209&pcsi=12746475122430218209,1',
#    'http://maps.google.com/maps/place?hl=en&expIds=25657,25901,26446,26515&sugexp=ldymls&xhr=t&cp=15gl=us&um=1&ie=UTF-8&q=il+fornaio+santa+monica&fb=1&gl=us&hq=il+fornaio&hnear=Santa+Monica,+CA&cid=18381072277423779130&pcsi=18381072277423779130,1',
#    'http://maps.google.com/maps/place?hl=en&gl=us&um=1&ie=UTF-&q=il+fornaio+seattle+wa&fb=1&gl=us&hq=il+fornaio&hnear=Seattle,+WA&cid=13183859282908290425&pcsi=13183859282908290425,1',
#    'http://maps.google.com/maps/place?hl=en&gl=us&um=1&ie=UTF-&q=il+fornaio+walnut+creek+ca&fb=1&gl=us&hq=il+fornaio&hnear=Walnut+Creek,+CA&cid=18128176857501020705&pcsi=18128176857501020705,1'
#    ]

OPENTABLE_URLS = [
    ('Beverly Hills', 'http://www.opentable.com/il-fornaio-beverly-hills'),
    ('Burlingame', 'http://www.opentable.com/il-fornaio-burlingame'),
    ('Carmel', 'http://www.opentable.com/il-fornaio-carmel-by-the-sea'),
    ('Coronado', 'http://www.opentable.com/il-fornaio-coronado'),
    ('Corte Madera', 'http://www.opentable.com/il-fornaio-corte-madera'),
    ('Del Mar', 'http://www.opentable.com/il-fornaio-del-mar'),
    ('Greenwood Village', 'http://www.opentable.com/il-fornaio-greenwood-village'),
    ('Irvine', 'http://www.opentable.com/il-fornaio-irvine'),
    ('Las Vegas', 'http://www.opentable.com/il-fornaio-las-vegas'),
    ('Canaletto Las Vegas', 'http://www.opentable.com/canaletto'),
    ('Manhattan Beach', 'http://www.opentable.com/il-fornaio-manhattan-beach'),
    ('Canaletto Newport Beach', 'http://www.opentable.com/canaletto-ristorante-veneto'),
    ('Palo Alto', 'http://www.opentable.com/il-fornaio-palo-alto'),
    ('Pasadena', 'http://www.opentable.com/il-fornaio-pasadena'),
    ('Reston', 'http://www.opentable.com/il-fornaio-reston'),
    ('Roseville', 'http://www.opentable.com/il-fornaio-roseville'),
    ('Sacramento', 'http://www.opentable.com/il-fornaio-sacramento'),
    ('San Francisco', 'http://www.opentable.com/il-fornaio-san-francisco'),
    ('San Jose', 'http://www.opentable.com/il-fornaio-san-jose'),
    ('Santa Monica', 'http://www.opentable.com/il-fornaio-santa-monica'),
    ('Seattle', 'http://www.opentable.com/il-fornaio-seattle'),
    ('Walnut Creek', 'http://www.opentable.com/il-fornaio-walnut-creek')
    ]

TRIPADVISOR_URLS = [
    ('Beverly Hills',
     'http://www.tripadvisor.com/Restaurant_Review-g32070-d348053-Reviews-Il_Fornaio-Beverly_Hills_California.html'),
    ('Burlingame',
     'http://www.tripadvisor.com/Restaurant_Review-g32124-d364892-Reviews-Il_Fornaio-Burlingame_California.html'),
    ('Carmel',
     'http://www.tripadvisor.com/Restaurant_Review-g32172-d491913-Reviews-Il_Fornaio-Carmel_Monterey_Peninsula_California.html'),
    ('Coronado',
     'http://www.tripadvisor.com/Restaurant_Review-g32250-d849686-Reviews-Il_Fornaio-Coronado_California.html'),
    ('Corte Madera',
     'http://www.tripadvisor.com/Restaurant_Review-g32252-d496392-Reviews-Il_Fornaio-Corte_Madera_Marin_County_California.html'),
    ('Del Mar',
     'http://www.tripadvisor.com/Restaurant_Review-g32286-d495235-Reviews-Il_Fornaio-Del_Mar_California.html'),
    ('Greenwood Village',
     'http://www.tripadvisor.com/Restaurant_Review-g33456-d382451-Reviews-Il_Fornaio-Greenwood_Village_Colorado.html'),
    ('Irvine',
     'http://www.tripadvisor.com/Restaurant_Review-g32530-d341637-Reviews-Il_Fornaio-Irvine_California.html'),
    ('Las Vegas',
     'http://www.tripadvisor.com/Restaurant_Review-g45963-d479166-Reviews-Il_Fornaio-Las_Vegas_Nevada.html'),
    ('Canaletto Las Vegas',
     'http://www.tripadvisor.com/Restaurant_Review-gf45963-d422688-Reviews-Canaletto-Las_Vegas_Nevada.html'),
    ('Manhattan Beach',
     'http://www.tripadvisor.com/Restaurant_Review-g32678-d358095-Reviews-Il_Fornaio-Manhattan_Beach_California.html'),
    ('Canaletto Newport Beach',
     'http://www.tripadvisor.com/Restaurant_Review-g32780-d1234060-Reviews-Canaletto-Newport_Beach_California.html'),
    ('Palo Alto',
     'http://www.tripadvisor.com/Restaurant_Review-g32849-d364532-Reviews-Il_Fornaio-Palo_Alto_California.htmll'),
    ('Pasadena',
     'http://www.tripadvisor.com/Restaurant_Review-g32859-d343314-Reviews-Il_Fornaio-Pasadena_California.html'),
    ('Reston',
     'http://www.tripadvisor.com/Restaurant_Review-g58120-d677498-Reviews-Il_Fornaio-Reston_Virginia.html'),
    ('Roseville',
     'http://www.tripadvisor.com/Restaurant_Review-g32988-d469120-Reviews-Il_Fornaio-Roseville_California.html'),
    ('Sacramento',
     'http://www.tripadvisor.com/Restaurant_Review-g32999-d339736-Reviews-Il_Fornaio-Sacramento_California.html'),
    ('San Francisco',
     'http://www.tripadvisor.com/Restaurant_Review-g60713-d354025-Reviews-Il_Fornaio-San_Francisco_California.html'),
    ('San Jose',
     'http://www.tripadvisor.com/Restaurant_Review-g33020-d491985-Reviews-Il_Fornaio-San_Jose_California.html'),
    ('Santa Monica',
     'http://www.tripadvisor.com/Restaurant_Review-g33052-d350224-Reviews-Il_Fornaio-Santa_Monica_California.html'),
    ('Seattle',
     'http://www.tripadvisor.com/Restaurant_Review-g60878-d432703-Reviews-Il_Fornaio-Seattle_Washington.html'),
    ('Walnut Creek',
     'http://www.tripadvisor.com/Restaurant_Review-g33235-d510560-Reviews-Il_Fornaio-Walnut_Creek_California.html')
    ]

URBANSPOON_URLS = [
    ('Beverly Hills',
     'http://www.urbanspoon.com/r/5/67475/restaurant/LA/Il-Fornaio-Beverly-Hills'),
    ('Burlingame',
     'http://www.urbanspoon.com/r/6/85181/restaurant/Il-Fornaio-Burlingame'),
    ('Carmel',
     'http://www.urbanspoon.com/r/277/1434103/restaurant/Salinas/Carmel/Il-Fornaio-Pine-Inn-Carmel-By-the-Sea'),
    ('Coronado',
     'http://www.urbanspoon.com/r/27/312269/restaurant/San-Diego/Il-Fornaio-Coronado'),
    ('Corte Madera',
     'http://www.urbanspoon.com/r/6/85180/restaurant/Il-Fornaio-Corte-Madera'),
    ('Del Mar',
     'http://www.urbanspoon.com/r/27/312270/restaurant/San-Diego/Il-Fornaio-Del-Mar'),
    ('Greenwood Village',
     'http://www.urbanspoon.com/r/17/212522/restaurant/Denver/Il-Fornaio-Greenwood-Village'),
    ('Irvine',
     'http://www.urbanspoon.com/r/20/243895/restaurant/OC/Il-Fornaio-Irvine'),
    ('Las Vegas',
     'http://www.urbanspoon.com/r/18/221564/restaurant/The-Strip/Il-Fornaio-New-York-New-York-Las-Vegas'),
    ('Canaletto Las Vegas',
     'http://www.urbanspoon.com/r/18/220498/restaurant/The-Strip/Canaletto-Venetian-Las-Vegas'),
    ('Manhattan Beach',
     'http://www.urbanspoon.com/r/5/67473/restaurant/LA/El-Segundo/Il-Fornaio-Manhattan-Beach'),
    ('Canaletto Newport Beach',
     'http://www.urbanspoon.com/r/20/1344676/restaurant/OC/Canaletto-Newport-Beach'),
    ('Palo Alto',
     'http://www.urbanspoon.com/r/6/85184/restaurant/Il-Fornaio-Palo-Alto'),
    ('Pasadena',
     'http://www.urbanspoon.com/r/5/67474/restaurant/LA/Il-Fornaio-Pasadena'),
    ('Reston',
     'http://www.urbanspoon.com/r/7/334423/restaurant/DC/Reston-Herndon/Il-Fornaio-Reston'),
    ('Roseville',
     'http://www.urbanspoon.com/r/36/401234/restaurant/Sacramento/Il-Fornaio-Roseville'),
    ('Sacramento',
     'http://www.urbanspoon.com/r/36/401233/restaurant/Downtown/Il-Fornaio-Sacramento'),
    ('San Francisco',
     'http://www.urbanspoon.com/r/6/85179/restaurant/North-Beach/Il-Fornaio-San-Francisco'),
    ('San Jose',
     'http://www.urbanspoon.com/r/6/85183/restaurant/Il-Fornaio-San-Jose'),
    ('Santa Monica',
     'http://www.urbanspoon.com/r/5/67472/restaurant/LA/Il-Fornaio-Santa-Monica'),
    ('Seattle',
     'http://www.urbanspoon.com/r/1/285/restaurant/Downtown/Il-Fornaio-Seattle'),
    ('Walnut Creek',
     'http://www.urbanspoon.com/r/6/764079/restaurant/Il-Fornaio-Walnut-Creek')
    ]

YELP_URLS = [
    ('Beverly Hills', 'http://www.yelp.com/biz/il-fornaio-beverly-hills'),
    ('Burlingame', 'http://www.yelp.com/biz/il-fornaio-burlingame'),
    ('Carmel', 'http://www.yelp.com/biz/il-fornaio-carmel'),
    ('Coronado', 'http://www.yelp.com/biz/il-fornaio-coronado-2'),
    ('Corte Madera', 'http://www.yelp.com/biz/il-fornaio-corte-madera'),
    ('Del Mar', 'http://www.yelp.com/biz/il-fornaio-del-mar'),
    ('Greenwood Village', 'http://www.yelp.com/biz/il-fornaio-greenwood-village-2'),
    ('Irvine', 'http://www.yelp.com/biz/il-fornaio-irvine'),
    ('Las Vegas', 'http://www.yelp.com/biz/il-fornaio-las-vegas'),
    ('Canaletto Las Vegas', 'http://www.yelp.com/biz/canaletto-las-vegas'),
    ('Manhattan Beach', 'http://www.yelp.com/biz/il-fornaio-manhattan-beach'),
    ('Canaletto Newport Beach', 'http://www.yelp.com/biz/canaletto-ristorante-veneto-newport-beach'),
    ('Palo Alto', 'http://www.yelp.com/biz/il-fornaio-palo-alto'),
    ('Pasadena', 'http://www.yelp.com/biz/il-fornaio-pasadena'),
    ('Reston', 'http://www.yelp.com/biz/il-fornaio-reston'),
    ('Roseville', 'http://www.yelp.com/biz/il-fornaio-roseville'),
    ('Sacramento', 'http://www.yelp.com/biz/il-fornaio-sacramento'),
    ('San Francisco', 'http://www.yelp.com/biz/il-fornaio-san-francisco'),
    ('San Jose', 'http://www.yelp.com/biz/il-fornaio-san-jose-3'),
    ('Santa Monica', 'http://www.yelp.com/biz/il-fornaio-restaurant-and-bakery-santa-monica'),
    ('Seattle', 'http://www.yelp.com/biz/il-fornaio-seattle'),
    ('Walnut Creek', 'http://www.yelp.com/biz/il-fornaio-walnut-creek')
    ]

SITES = {
    'CitySearch': CITYSEARCH_URLS,
    #'Google': GOOGLE_URLS,
    'OpenTable': OPENTABLE_URLS,
    'TripAdvisor': TRIPADVISOR_URLS,
    'UrbanSpoon': URBANSPOON_URLS,
    'Yelp': YELP_URLS,
    'Zagat': ZAGAT_URLS
    }
